// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackEndAngular.Models;

public partial class Funcionario
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    
    [StringLength(150)]
    [Unicode(false)]
    public string Endereco { get; set; }

    public DateTime? DataNascimento { get; set; }

    public bool? Ativo { get; set; }
}